import { Item } from "./Item";

export const data: Item[] = [
  {
    id: "qr-code-component",
    name: "QR code component",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam a dapibus mi, nec pulvinar odio. Quisque quis nunc lacinia, vestibulum enim ut, accumsan metus.  ",
    tags: [],
    type: "start",
    tutorialUrl: "https://www.youtube.com/watch?v=5BBYPntB-GY&t=7s",
    statementUrl:
      "https://www.frontendmentor.io/challenges/qr-code-component-iux_sIO_H",
    githubUrl: "https://github.com/SofiaBargues/qr-code-component",
    demoUrl: "https://qr-code-component-liart.vercel.app/",
    imgSource: "/qr-code-component.jpg",
  },
  {
    id: "blog-preview-card",
    name: "Blog Preview Card",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=3n22cowxoKU",
    statementUrl:
      "https://www.frontendmentor.io/challenges/blog-preview-card-ckPaj01IcS",
    githubUrl: "https://github.com/SofiaBargues/blog-preview-card",
    demoUrl: "https://blog-preview-card-xi-gules.vercel.app/",
    imgSource: "/blog-preview-card.jpg",
  },
  {
    id: "social-links-profile",
    name: "Social links profile",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=PlUOMi23qAc",
    statementUrl:
      "https://www.frontendmentor.io/challenges/social-links-profile-UG32l9m6dQ",
    githubUrl: "https://github.com/SofiaBargues/social-links-profile-main",
    demoUrl: "https://social-links-profile-main-yycc.vercel.app/",
    imgSource: "/social-links-profile.jpg",
  },
  {
    id: "recipe-page",
    name: "Recipe page",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=wF2DLQGeJS0&t=185s",
    statementUrl:
      "https://www.frontendmentor.io/challenges/recipe-page-KiTsR8QQKm",
    githubUrl: "https://github.com/SofiaBargues/recipe-page",
    demoUrl: "https://recipe-page-alpha-ten.vercel.app/",
    imgSource: "/recipe-page.jpg",
  },
  {
    id: "testimonials-grid-section",
    name: "Testimonials grid",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl:
      "https://www.youtube.com/watch?v=0TiIJjC7Olw&list=PLrVXEY3WfL-39_2q2HiKkuyNxelQI1XeV",
    statementUrl:
      "https://www.frontendmentor.io/challenges/testimonials-grid-section-Nnw6J7Un7",
    githubUrl: "https://github.com/SofiaBargues/testimonialsgrid-section",
    demoUrl:
      "https://testimonialsgrid-section-git-main-sofiabargues-projects.vercel.app/",
    imgSource: "/testimonials-grid-section.jpg",
  },
  {
    id: "article-preview-component",
    name: "Article preview",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl:
      "https://www.youtube.com/watch?v=SKhZ0IBk1_A&list=PLrVXEY3WfL-39_2q2HiKkuyNxelQI1XeV&index=2",
    statementUrl:
      "https://www.frontendmentor.io/learning-paths/javascript-fundamentals-oR7g6-mTZ-/steps/665e1b4e6ec3887a3b142b16/challenge/start",
    githubUrl: "https://github.com/SofiaBargues/article-preview-component",
    demoUrl: "https://article-preview-component-sable.vercel.app/",
    imgSource: "/article-preview.jpg",
  },
  {
    id: "time-tracking-dashboard",
    name: "Time tracking",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=l9Qw8y3LfCY",
    statementUrl:
      "https://www.frontendmentor.io/challenges/time-tracking-dashboard-UIQ7167Jw",
    githubUrl: "https://github.com/SofiaBargues/time-tracking-dashboard",
    demoUrl: "https://time-tracking-dashboard-pied.vercel.app/",
    imgSource: "/time-tracking-dashboard.jpg",
  },
  {
    id: "newsletter-sign-up-form-with-success-message",
    name: "Newsletter sign-up",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl:
      "https://www.youtube.com/watch?v=abdsoVJsWzQ&list=PLrVXEY3WfL-39_2q2HiKkuyNxelQI1XeV&index=3",
    statementUrl:
      "https://www.frontendmentor.io/challenges/newsletter-signup-form-with-success-message-3FC1AZbNrv/hub",
    githubUrl: "https://github.com/SofiaBargues/newsletter-sign-up",
    demoUrl: "https://frontend-mentor-newsletter-signup-form-ruby.vercel.app/",
    imgSource: "/newsletter-singup-form.jpg",
  },
  {
    id: "expenses-chart-component",
    name: "Expenses chart",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=s9CHPlY8J8I",
    statementUrl:
      "https://www.frontendmentor.io/challenges/expenses-chart-component-e7yJBUdjwt",
    githubUrl: "https://github.com/SofiaBargues/expensesChartComponent",
    demoUrl: "https://expenses-chart-component-rho-amber.vercel.app/",
    imgSource: "/expenses-chart-component.jpg",
  },
  {
    id: "tip-calculator",
    name: "Tip calculator",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=FYCauVeo8OY",
    statementUrl:
      "https://www.frontendmentor.io/challenges/tip-calculator-app-ugJNGbJUX",
    githubUrl: "https://github.com/SofiaBargues/tip-calculator-app-main",
    demoUrl: "https://tip-calculator-app-main-ivory.vercel.app/",
    imgSource: "/tip-calculator-app.jpg",
  },
  {
    id: "pricing-component-with-toggle",
    name: "Pricing component",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=u02jD-Sj4yg",
    statementUrl:
      "https://www.frontendmentor.io/challenges/pricing-component-with-toggle-8vPwRMIC",
    githubUrl: "https://github.com/SofiaBargues/pricing-component-with-toggle",
    demoUrl: "https://pricing-component-with-toggle-two-phi.vercel.app/",
    imgSource: "/pricing-component-with-toggle.jpg",
  },
  {
    id: "age-calculator-app",
    name: "Age calculator app",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=3n22cowxoKU",
    statementUrl:
      "https://www.frontendmentor.io/challenges/age-calculator-app-dF9DFFpj-Q",
    githubUrl: "https://github.com/SofiaBargues/age-calculator-app-main",
    demoUrl: "https://age-calculator-app-main-psi.vercel.app/",
    imgSource: "/age-calculator-app.jpg",
  },

  {
    id: "interactive-pricing-component",
    name: "Interactive pricing",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=dg7vy9FzFUo",
    statementUrl:
      "https://www.frontendmentor.io/challenges/interactive-pricing-component-t0m8PIyY8",
    githubUrl: "https://github.com/SofiaBargues/interactive-pricing-component",
    demoUrl: "https://interactive-pricing-component-six-kappa.vercel.app/",
    imgSource: "/interactive-pricing-component.jpg",
  },
  {
    id: "advice-generator",
    name: "Advice generator app",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "",
    statementUrl:
      "https://www.frontendmentor.io/challenges/advice-generator-app-QdUG-13db",
    githubUrl: "https://github.com/SofiaBargues/advice-generator-app",
    demoUrl: "https://advice-generator-app-tau-six.vercel.app/",
    imgSource: "/advice-generator.jpg",
  },
  {
    id: "ip-address-tracker",
    name: "Advice generator app",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "",
    statementUrl:
      "https://www.frontendmentor.io/challenges/ip-address-tracker-I8-0yYAH0",
    githubUrl: "https://github.com/SofiaBargues/ip-address-tracker-1",
    demoUrl: "https://ip-address-tracker-1.vercel.app/",
    imgSource: "/ip-address-tracker.jpg",
  },
  {
    id: "accordion-component",
    name: "Accordion Component",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=dkh9-zICMQg&t=504s",
    statementUrl:
      "https://devtools.tech/questions/s/implement-accordion-component-in-reactjs-or-javascript-interview-question---qid---3pRN4mOqn69FJ94mrh1A",
    githubUrl: "https://github.com/SofiaBargues/accordion-component",
    demoUrl: "https://accordion-component-bay.vercel.app/",
    imgSource: "/accordion-component.png",
  },
  {
    id: "country-capital-game",
    name: "Country Capital Game",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "",
    statementUrl:
      "https://devtools.tech/questions/s/build-country-capital-game-or-microsoft-frontend-interview-question-or-javascript-or-react-js---qid---yPb5g7MLCSf6j2F3qjqj",
    githubUrl: "https://github.com/SofiaBargues/country-capital-game",
    demoUrl: "https://country-capital-game-gamma.vercel.app/",
    imgSource: "/country-capital-game.webp",
  },
  {
    id: "confluence-like-sidebar",
    name: "Confluence-like Sidebar",
    description:
      "In this question, the candidate needs to build a sidebar that contains a collapsible tree-like UI.",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=3OxMsnP78zg",
    statementUrl:
      "https://www.devtools.tech/questions/s/how-to-build-a-confluence-like-sidebar-with-tree-structure-or-atlassian-frontend-interview-question-or-react-js---qid---3r7988VsESMQBt9vP1Zi",
    githubUrl: "https://github.com/SofiaBargues/confluence-like-sidebar",
    demoUrl: "https://confluence-like-sidebar.vercel.app/",
    imgSource: "/confluence-like-sidebar.webp",
  },
  {
    id: "password-strength-checker",
    name: "Password Strength Checker",
    description:
      "In this question, you need to build a password strength checker in React.js that shows the strength of the password.",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=CM-MXPl0-wE",
    statementUrl:
      "https://www.devtools.tech/questions/s/how-to-build-a-password-strength-checker-in-react-js-or-frontend-interview-question-or-javascript---qid---tQR3mRIXsSK1tDfCliYj",
    githubUrl: "https://github.com/SofiaBargues/password-strength-checker",
    demoUrl: "https://password-strength-checker-red.vercel.app/",
    imgSource: "/password-strength-checker.png",
  },
  {
    id: "text-autocomplete",
    name: "Text Autocomplete",
    description:
      "In this coding challenge, you need to build an autocomplete that will act as a payment page where users can enter their UPI.",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=qMkUziVZvzs",
    statementUrl:
      "https://www.devtools.tech/questions/s/build-an-autocomplete-using-reactjs-or-type-one-or-frontend-coding-challenge-or-javascript-interview-question---qid---wIsJwxPV1Ka0GdmTIXQX",
    githubUrl: "https://github.com/SofiaBargues/autocomplete",
    demoUrl: "https://autocomplete-6ix2.vercel.app/",
    imgSource: "/autocomplete.png",
  },
  {
    id: "circles-game",
    name: "Circles Game",
    description:
      "In this UI coding challenge, the candidate needs to build a simple React app where a circle should appear wherever user clicks on the screen.",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/watch?v=h05uGv0PEuQ",
    statementUrl:
      "https://www.devtools.tech/questions/s/how-to-build-circles-game-in-react-js-frontend-coding-challenge---qid---Y8acly7B5CmIVAaT5knP",
    githubUrl: "https://github.com/SofiaBargues/circles-game",
    demoUrl: "https://circles-game.vercel.app/",
    imgSource: "/circles-game.png",
  },
  {
    id: "Coming soon",
    name: "Coming soon",
    description: "Here the description",
    type: "start",
    tags: [],
    tutorialUrl: "https://www.youtube.com/",
    statementUrl: "https://www.frontendmentor.io",
    githubUrl: "https://github.com/SofiaBargues",
    demoUrl: "https://frontend-30.vercel.app/",
    imgSource:
      "https://www.practiceportuguese.com/cdn-cgi/image/width=800,quality=90,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2020/06/asking-questions-800x534.jpg",
  },
];
